import React, { useState, useEffect } from 'react';
import { createLegalDocumentApi } from '../../../../../shared/api/admin/legal.api.js';
import { DOCUMENT_TYPES, TARGET_ROLES } from '../../../../../shared/constants/legal.constants.js';
import RichTextEditor from "../../../../../shared/components/RichTextEditor/RichTextEditor";

const CreateDocumentModal = ({ isOpen, onClose, onCreated }) => {
    const [formData, setFormData] = useState({
        title: '',
        slug: '',
        document_type: '',
        target_role: '',
        content: '',
        require_acceptance: true,
        require_signature: false,
        change_log: ''
    });
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [errors, setErrors] = useState([]);
    const [isSlugAutoGenerated, setIsSlugAutoGenerated] = useState(true);

    // Auto-generate slug from title
    useEffect(() => {
        if (isSlugAutoGenerated && formData.title) {
            const generatedSlug = formData.title
                .toLowerCase()
                .replace(/[^a-z0-9\s-]/g, '')
                .replace(/\s+/g, '-')
                .replace(/-+/g, '-')
                .replace(/^-|-$/g, '');
            setFormData(prev => ({ ...prev, slug: generatedSlug }));
        }
    }, [formData.title, isSlugAutoGenerated]);

    if (!isOpen) return null;

    const handleChange = (field, value) => {
        setFormData(prev => ({ ...prev, [field]: value }));
        setErrors([]);
        
        if (field === 'slug') {
            setIsSlugAutoGenerated(false);
        }
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        setIsSubmitting(true);
        setErrors([]);

        try {
            const response = await createLegalDocumentApi(formData);
            if (response.success) {
                onCreated(response.data);
                onClose();
                // Reset form
                setFormData({
                    title: '',
                    slug: '',
                    document_type: '',
                    target_role: '',
                    content: '',
                    require_acceptance: true,
                    require_signature: false,
                    change_log: ''
                });
                setIsSlugAutoGenerated(true);
            }
        } catch (error) {
            console.error('Creation failed:', error);
            if (error.response?.data?.errors) {
                setErrors(error.response.data.errors);
            } else if (error.response?.data?.message) {
                setErrors([error.response.data.message]);
            } else {
                setErrors(['Failed to create document. Please try again.']);
            }
        } finally {
            setIsSubmitting(false);
        }
    };

    const docTypeOptions = Object.keys(DOCUMENT_TYPES).map(key => ({
        label: key.replace(/_/g, ' ').toLowerCase().replace(/\b\w/g, l => l.toUpperCase()),
        value: DOCUMENT_TYPES[key]
    }));

    const roleOptions = Object.keys(TARGET_ROLES).map(key => ({
        label: key.charAt(0).toUpperCase() + key.slice(1).toLowerCase(),
        value: TARGET_ROLES[key]
    }));

    return (
        <div style={styles.overlay} onClick={onClose}>
            <div style={styles.modal} onClick={(e) => e.stopPropagation()}>
                <div style={styles.header}>
                    <h2 style={styles.title}>📄 Create Legal Document</h2>
                    <button style={styles.closeButton} onClick={onClose}>✕</button>
                </div>

                <form onSubmit={handleSubmit} style={styles.form}>
                    <div style={styles.grid}>
                        {/* Title */}
                        <div style={styles.field}>
                            <label style={styles.label}>Title *</label>
                            <input
                                type="text"
                                value={formData.title}
                                onChange={(e) => handleChange('title', e.target.value)}
                                style={styles.input}
                                placeholder="Enter document title"
                                required
                            />
                        </div>

                        {/* Slug */}
                        <div style={styles.field}>
                            <label style={styles.label}>Slug</label>
                            <div style={styles.slugContainer}>
                                <input
                                    type="text"
                                    value={formData.slug}
                                    onChange={(e) => handleChange('slug', e.target.value)}
                                    style={styles.input}
                                    placeholder="url-friendly-slug"
                                />
                                <button
                                    type="button"
                                    style={{
                                        ...styles.slugAutoBtn,
                                        ...(isSlugAutoGenerated ? styles.slugAutoBtnActive : {})
                                    }}
                                    onClick={() => {
                                        setIsSlugAutoGenerated(!isSlugAutoGenerated);
                                        if (!isSlugAutoGenerated && formData.title) {
                                            const generatedSlug = formData.title
                                                .toLowerCase()
                                                .replace(/[^a-z0-9\s-]/g, '')
                                                .replace(/\s+/g, '-')
                                                .replace(/-+/g, '-')
                                                .replace(/^-|-$/g, '');
                                            setFormData(prev => ({ ...prev, slug: generatedSlug }));
                                        }
                                    }}
                                    title={isSlugAutoGenerated ? 'Auto-generate on' : 'Auto-generate off'}
                                >
                                    🔄
                                </button>
                            </div>
                        </div>

                        {/* Document Type */}
                        <div style={styles.field}>
                            <label style={styles.label}>Document Type *</label>
                            <select
                                value={formData.document_type}
                                onChange={(e) => handleChange('document_type', e.target.value)}
                                style={styles.select}
                                required
                            >
                                <option value="">Select type...</option>
                                {docTypeOptions.map(opt => (
                                    <option key={opt.value} value={opt.value}>{opt.label}</option>
                                ))}
                            </select>
                        </div>

                        {/* Target Role */}
                        <div style={styles.field}>
                            <label style={styles.label}>Target Role *</label>
                            <select
                                value={formData.target_role}
                                onChange={(e) => handleChange('target_role', e.target.value)}
                                style={styles.select}
                                required
                            >
                                <option value="">Select role...</option>
                                {roleOptions.map(opt => (
                                    <option key={opt.value} value={opt.value}>{opt.label}</option>
                                ))}
                            </select>
                        </div>

                        {/* Content */}
                        <div style={styles.fieldFull}>
                            <label style={styles.label}>Content *</label>
                            <div style={styles.editorWrapper}>
                                <RichTextEditor
                                    value={formData.content}
                                    editable={true}
                                    onChange={(html) => handleChange('content', html)}
                                    placeholder="Write the document content here..."
                                />
                            </div>
                        </div>

                        {/* Change Log */}
                        <div style={styles.field}>
                            <label style={styles.label}>Change Log</label>
                            <input
                                type="text"
                                value={formData.change_log}
                                onChange={(e) => handleChange('change_log', e.target.value)}
                                style={styles.input}
                                placeholder="Describe the initial version"
                            />
                        </div>

                        {/* Require Acceptance */}
                        <div style={styles.field}>
                            <label style={styles.label}>Require Acceptance</label>
                            <div style={styles.toggleGroup}>
                                <button
                                    type="button"
                                    style={{
                                        ...styles.toggleButton,
                                        ...(formData.require_acceptance ? styles.toggleButtonActive : {})
                                    }}
                                    onClick={() => handleChange('require_acceptance', true)}
                                >
                                    Yes
                                </button>
                                <button
                                    type="button"
                                    style={{
                                        ...styles.toggleButton,
                                        ...(!formData.require_acceptance ? styles.toggleButtonActive : {})
                                    }}
                                    onClick={() => handleChange('require_acceptance', false)}
                                >
                                    No
                                </button>
                            </div>
                        </div>

                        {/* Require Signature */}
                        <div style={styles.field}>
                            <label style={styles.label}>Require Signature</label>
                            <div style={styles.toggleGroup}>
                                <button
                                    type="button"
                                    style={{
                                        ...styles.toggleButton,
                                        ...(formData.require_signature ? styles.toggleButtonActive : {})
                                    }}
                                    onClick={() => handleChange('require_signature', true)}
                                >
                                    Yes
                                </button>
                                <button
                                    type="button"
                                    style={{
                                        ...styles.toggleButton,
                                        ...(!formData.require_signature ? styles.toggleButtonActive : {})
                                    }}
                                    onClick={() => handleChange('require_signature', false)}
                                >
                                    No
                                </button>
                            </div>
                        </div>
                    </div>

                    {/* Errors */}
                    {errors.length > 0 && (
                        <div style={styles.errorContainer}>
                            {errors.map((err, i) => (
                                <div key={i} style={styles.errorItem}>⚠️ {err}</div>
                            ))}
                        </div>
                    )}

                    {/* Actions */}
                    <div style={styles.actions}>
                        <button
                            type="button"
                            style={styles.cancelButton}
                            onClick={onClose}
                        >
                            Cancel
                        </button>
                        <button
                            type="submit"
                            disabled={isSubmitting}
                            style={{
                                ...styles.createButton,
                                ...(isSubmitting ? styles.createButtonDisabled : {})
                            }}
                        >
                            {isSubmitting ? 'Creating...' : '✨ Create Document'}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
};

const styles = {
    overlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.5)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 9999,
        padding: '20px'
    },
    modal: {
        backgroundColor: '#fff',
        borderRadius: '12px',
        maxWidth: '800px',
        width: '100%',
        maxHeight: '90vh',
        overflow: 'auto',
        padding: '24px',
        boxShadow: '0 20px 60px rgba(0,0,0,0.3)'
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '20px'
    },
    title: {
        fontSize: '20px',
        fontWeight: '600',
        color: '#1a2332',
        margin: 0
    },
    closeButton: {
        padding: '4px 8px',
        border: 'none',
        background: 'none',
        fontSize: '20px',
        color: '#6b7280',
        cursor: 'pointer'
    },
    form: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px'
    },
    grid: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: '16px'
    },
    field: {
        display: 'flex',
        flexDirection: 'column',
        gap: '6px'
    },
    fieldFull: {
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
        gridColumn: '1 / -1'
    },
    label: {
        fontSize: '13px',
        fontWeight: '500',
        color: '#374151'
    },
    input: {
        padding: '10px 12px',
        border: '1px solid #e5e7eb',
        borderRadius: '8px',
        fontSize: '14px',
        outline: 'none',
        transition: 'border-color 0.2s',
        width: '100%',
        boxSizing: 'border-box'
    },
    select: {
        padding: '10px 12px',
        border: '1px solid #e5e7eb',
        borderRadius: '8px',
        fontSize: '14px',
        outline: 'none',
        backgroundColor: '#fff',
        transition: 'border-color 0.2s',
        width: '100%'
    },
    slugContainer: {
        display: 'flex',
        gap: '8px',
        alignItems: 'center'
    },
    slugAutoBtn: {
        padding: '8px 12px',
        border: '1px solid #e5e7eb',
        borderRadius: '8px',
        backgroundColor: '#fff',
        cursor: 'pointer',
        fontSize: '16px',
        transition: 'all 0.2s',
        flexShrink: 0
    },
    slugAutoBtnActive: {
        backgroundColor: '#eef2ff',
        borderColor: '#4f46e5'
    },
    editorWrapper: {
        border: '1px solid #e5e7eb',
        borderRadius: '8px',
        overflow: 'hidden'
    },
    toggleGroup: {
        display: 'flex',
        gap: '4px',
        backgroundColor: '#f3f4f6',
        borderRadius: '8px',
        padding: '3px'
    },
    toggleButton: {
        padding: '6px 16px',
        border: 'none',
        borderRadius: '6px',
        fontSize: '13px',
        fontWeight: '500',
        cursor: 'pointer',
        transition: 'all 0.2s',
        backgroundColor: 'transparent',
        color: '#6b7280'
    },
    toggleButtonActive: {
        backgroundColor: '#fff',
        color: '#1a2332',
        boxShadow: '0 1px 3px rgba(0,0,0,0.1)'
    },
    errorContainer: {
        padding: '12px',
        backgroundColor: '#fef2f2',
        borderRadius: '8px',
        border: '1px solid #fecaca'
    },
    errorItem: {
        fontSize: '14px',
        color: '#991b1b',
        padding: '2px 0'
    },
    actions: {
        display: 'flex',
        justifyContent: 'flex-end',
        gap: '12px',
        borderTop: '1px solid #e5e7eb',
        paddingTop: '16px'
    },
    cancelButton: {
        padding: '10px 24px',
        backgroundColor: '#f3f4f6',
        color: '#1a2332',
        border: 'none',
        borderRadius: '8px',
        fontSize: '14px',
        fontWeight: '500',
        cursor: 'pointer',
        transition: 'background-color 0.2s'
    },
    createButton: {
        padding: '10px 24px',
        backgroundColor: '#4f46e5',
        color: '#fff',
        border: 'none',
        borderRadius: '8px',
        fontSize: '14px',
        fontWeight: '500',
        cursor: 'pointer',
        transition: 'background-color 0.2s'
    },
    createButtonDisabled: {
        backgroundColor: '#a5b4fc',
        cursor: 'not-allowed',
        opacity: 0.6
    }
};

export default CreateDocumentModal;