// src/apps/user/components/userExperts/aiExpertsData.js
import { v4 as uuid } from "uuid";

const baseImg =
  "https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg";

export const AI_EXPERTS = [
  {
    id: uuid(),
    isAI: true,
    name: "Aurora Career AI",
    role: "Career & Job Mentor",
    img: baseImg,
    rating: "5.0",
    reviews: 520,
    experienceYears: 0,
    languages: ["English", "Hindi"],
    chatPrice: 8,
    online: true,
  },
  {
    id: uuid(),
    isAI: true,
    name: "Lexi Law AI",
    role: "Legal & Contracts Assistant",
    img: baseImg,
    rating: "4.9",
    reviews: 410,
    experienceYears: 0,
    languages: ["English"],
    chatPrice: 10,
    online: true,
  },
  {
    id: uuid(),
    isAI: true,
    name: "Pulse Health AI",
    role: "General Health Guidance",
    img: baseImg,
    rating: "4.8",
    reviews: 360,
    experienceYears: 0,
    languages: ["English"],
    chatPrice: 7,
    online: true,
  },
  {
    id: uuid(),
    isAI: true,
    name: "MoneyMind AI",
    role: "Personal Finance & Budget",
    img: baseImg,
    rating: "4.9",
    reviews: 390,
    experienceYears: 0,
    languages: ["English", "Hindi"],
    chatPrice: 9,
    online: true,
  },
  {
    id: uuid(),
    isAI: true,
    name: "Startup Sensei AI",
    role: "Startup & Pitch Mentor",
    img: baseImg,
    rating: "4.8",
    reviews: 270,
    experienceYears: 0,
    languages: ["English"],
    chatPrice: 11,
    online: true,
  },
  {
    id: uuid(),
    isAI: true,
    name: "FitFlow AI",
    role: "Fitness & Nutrition Coach",
    img: baseImg,
    rating: "4.7",
    reviews: 220,
    experienceYears: 0,
    languages: ["English"],
    chatPrice: 6,
    online: true,
  },
  {
    id: uuid(),
    isAI: true,
    name: "CalmSpace AI",
    role: "Mental Wellness Companion",
    img: baseImg,
    rating: "4.9",
    reviews: 510,
    experienceYears: 0,
    languages: ["English"],
    chatPrice: 7,
    online: true,
  },
  {
    id: uuid(),
    isAI: true,
    name: "DesignMuse AI",
    role: "UI/UX & Branding Mentor",
    img: baseImg,
    rating: "4.8",
    reviews: 260,
    experienceYears: 0,
    languages: ["English"],
    chatPrice: 9,
    online: true,
  },
  {
    id: uuid(),
    isAI: true,
    name: "CodeBuddy AI",
    role: "Programming & Debugging Partner",
    img: baseImg,
    rating: "5.0",
    reviews: 640,
    experienceYears: 0,
    languages: ["English"],
    chatPrice: 8,
    online: true,
  },
  {
    id: uuid(),
    isAI: true,
    name: "AstroGuide AI",
    role: "Life & Astrology Guidance",
    img: baseImg,
    rating: "4.7",
    reviews: 190,
    experienceYears: 0,
    languages: ["English", "Hindi"],
    chatPrice: 6,
    online: true,
  },
];
