name: Auto Deploy Frontend

on:
  push:
    branches:
      - main
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: main
            deploy-name: guidexa
            api-url-secret: GUIDEXA_API_URL
            ftp-server-secret: GUIDEXA_FTP_SERVER
            ftp-username-secret: GUIDEXA_FTP_USERNAME
            ftp-password-secret: GUIDEXA_FTP_PASSWORD
            server-dir: /
          - branch: production
            deploy-name: g9expert
            api-url-secret: SOFTMAXS_API_URL
            ftp-server-secret: FTP_SERVER
            ftp-username-secret: FTP_USERNAME
            ftp-password-secret: FTP_PASSWORD
            server-dir: public_html/
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Download Sitemap
        run: |
          mkdir -p public
          curl -L http://softmaxs.com/sitemap.xml -o public/sitemap.xml

      - name: Build project with environment variables
        if: github.ref == format('refs/heads/{0}', matrix.branch)
        env:
          VITE_API_BASE_URL: ${{ secrets[matrix.api-url-secret] }}
        run: npm run build

      - name: Upload Build Artifact
        if: github.ref == format('refs/heads/{0}', matrix.branch)
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.deploy-name }}
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: main
            deploy-name: guidexa
            ftp-server-secret: GUIDEXA_FTP_SERVER
            ftp-username-secret: GUIDEXA_FTP_USERNAME
            ftp-password-secret: GUIDEXA_FTP_PASSWORD
            server-dir: /
          - branch: production
            deploy-name: g9expert
            ftp-server-secret: FTP_SERVER
            ftp-username-secret: FTP_USERNAME
            ftp-password-secret: FTP_PASSWORD
            server-dir: public_html/
    
    steps:
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: dist-${{ matrix.deploy-name }}
          path: dist

      - name: Deploy to ${{ matrix.deploy-name }}
        if: github.ref == format('refs/heads/{0}', matrix.branch)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets[matrix.ftp-server-secret] }}
          username: ${{ secrets[matrix.ftp-username-secret] }}
          password: ${{ secrets[matrix.ftp-password-secret] }}
          local-dir: dist/
          server-dir: ${{ matrix.server-dir }}
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/node_modules/