name: Auto Deploy Frontend

on:
  push:
    branches:
      - main
      - production

jobs:
  deploy-guidexa:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Download Sitemap
        run: |
          mkdir -p public
          curl -L http://softmaxs.com/sitemap.xml -o public/sitemap.xml

      - name: Build Guidexa
        env:
          VITE_API_BASE_URL: ${{ secrets.GUIDEXA_API_URL }}
        run: npm run build

      - name: Deploy to Guidexa
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.GUIDEXA_FTP_SERVER }}
          username: ${{ secrets.GUIDEXA_FTP_USERNAME }}
          password: ${{ secrets.GUIDEXA_FTP_PASSWORD }}
          local-dir: dist/
          server-dir: /
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/node_modules/**

  deploy-production:
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Download Sitemap
        run: |
          mkdir -p public
          curl -L http://softmaxs.com/sitemap.xml -o public/sitemap.xml

      - name: Build Softmaxs
        env:
          VITE_API_BASE_URL: ${{ secrets.SOFTMAXS_API_URL }}
        run: npm run build

      - name: Deploy to Softmaxs
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: public_html/
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/node_modules/**